// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/metered.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package metered

import (
	"context"

	"github.com/uber/cadence/common/config"
	"github.com/uber/cadence/common/log"
	"github.com/uber/cadence/common/metrics"
	"github.com/uber/cadence/common/persistence"
	_sourcePersistence "github.com/uber/cadence/common/persistence"
)

// meteredHistoryTaskDLQManager implements _sourcePersistence.HistoryTaskDLQManager interface instrumented with rate limiter.
type meteredHistoryTaskDLQManager struct {
	base
	wrapped _sourcePersistence.HistoryTaskDLQManager
}

// NewHistoryTaskDLQManager creates a new instance of HistoryTaskDLQManager with ratelimiter.
func NewHistoryTaskDLQManager(
	wrapped persistence.HistoryTaskDLQManager,
	metricClient metrics.Client,
	logger log.Logger,
	cfg *config.Persistence,
) persistence.HistoryTaskDLQManager {
	return &meteredHistoryTaskDLQManager{
		wrapped: wrapped,
		base: base{
			metricClient:                  metricClient,
			logger:                        logger,
			enableLatencyHistogramMetrics: cfg.EnablePersistenceLatencyHistogramMetrics,
			hostName:                      cfg.HostName,
		},
	}
}

func (c *meteredHistoryTaskDLQManager) Close() {
	c.wrapped.Close()
	return
}

func (c *meteredHistoryTaskDLQManager) CreateHistoryDLQTask(ctx context.Context, request _sourcePersistence.CreateHistoryDLQTaskRequest) (err error) {
	op := func() error {
		err = c.wrapped.CreateHistoryDLQTask(ctx, request)
		c.emptyMetric("HistoryTaskDLQManager.CreateHistoryDLQTask", request, err, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceCreateHistoryDLQTaskScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}

func (c *meteredHistoryTaskDLQManager) DeleteHistoryDLQTasks(ctx context.Context, request _sourcePersistence.HistoryDLQDeleteTasksRequest) (err error) {
	op := func() error {
		err = c.wrapped.DeleteHistoryDLQTasks(ctx, request)
		c.emptyMetric("HistoryTaskDLQManager.DeleteHistoryDLQTasks", request, err, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceDeleteHistoryDLQTasksScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}

func (c *meteredHistoryTaskDLQManager) GetHistoryDLQAckLevels(ctx context.Context, request _sourcePersistence.HistoryDLQGetAckLevelsRequest) (ha1 []_sourcePersistence.HistoryDLQAckLevel, err error) {
	op := func() error {
		ha1, err = c.wrapped.GetHistoryDLQAckLevels(ctx, request)
		c.emptyMetric("HistoryTaskDLQManager.GetHistoryDLQAckLevels", request, ha1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceGetHistoryDLQAckLevelsScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}

func (c *meteredHistoryTaskDLQManager) GetHistoryDLQTasks(ctx context.Context, request _sourcePersistence.HistoryDLQGetTasksRequest) (h1 _sourcePersistence.HistoryDLQGetTasksResponse, err error) {
	op := func() error {
		h1, err = c.wrapped.GetHistoryDLQTasks(ctx, request)
		c.emptyMetric("HistoryTaskDLQManager.GetHistoryDLQTasks", request, h1, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceGetHistoryDLQTasksScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}

func (c *meteredHistoryTaskDLQManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *meteredHistoryTaskDLQManager) UpdateHistoryDLQAckLevel(ctx context.Context, request _sourcePersistence.HistoryDLQUpdateAckLevelRequest) (err error) {
	op := func() error {
		err = c.wrapped.UpdateHistoryDLQAckLevel(ctx, request)
		c.emptyMetric("HistoryTaskDLQManager.UpdateHistoryDLQAckLevel", request, err, err)
		return err
	}

	retryCount := getRetryCountFromContext(ctx)

	err = c.call(metrics.PersistenceUpdateHistoryDLQAckLevelScope, op, append(getCustomMetricTags(request), metrics.IsRetryTag(retryCount > 0))...)
	return
}
